### ISSUE TITLE
difference between java and node in curve 25519 keypair signature

### ISSUE THREAD

**Issue by GavinEmali** [java-crypto/cross_platform_crypto#1]
Hi，I signed a string by the public key generated by curve 25519 key pair generation in java, and verified the signature in node, but the result is false . 
Is there any difference between java and node in Signature implementation？
Thank you 。

Gavin

**Comment by java-crypto** [comment]
Curve25519 in general is designed for an elliptic curve Diffie–Hellman (ECDH) key agreement scheme (see e.g. https://en.wikipedia.org/wiki/Curve25519) and **not** for signatures. For signatures I recommend the usage of Ed25519 curves. For examples in Java and NodeJs kindly visit my "Libsodium overview article" on [https://github.com/java-crypto/cross_platform_crypto/blob/main/docs/libsodium_overview.md](https://github.com/java-crypto/cross_platform_crypto/blob/main/docs/libsodium_overview.md).

**Comment by GavinEmali** [comment]
Thank you ，I will try Ed25519.
